const reportArr = {
  'olt-monthly': {
    headers: [
      'STATE',
      'DISTRICT',
      'BLOCK',
      'OLT LOCATION',
      'OLT LOCATION CODE',
      'OLT IP',
      'OLT NAME',
      'TOTAL DOWN TIME',
      'TOTAL UNREACHABLE TIME',
      'OLT AVAILABILITY(%)',
      'PHASE',
    ],
    columns: [
      'report_id',
      'gp_code',
      'state',
      'district',
      'block',
      'olt_location',
      'olt_location_code',
      'olt_ip',
      'olt_name',
      'total_down_time',
      'total_unreachable_time',
      'olt_availability',
      'phase',
    ],
  },
  'olt-net-provider': {
    headers: [
      'NETWORK PROVIDER',
      'DISTRICT',
      'BLOCK',
      'OLT LOCATION',
      'OLT LOCATION CODE',
      'OLT NAME',
      'OLT IP',
      'EMS NAME',
      'POINT ASSET CODE',
      'VENDOR',
      'TECH NAME',
      'VERSION',
      'OLT STATE',
      'STATE CHANGE TIME',
      'COMMISSION DATE',
      'NMS CONFIG DATE',
      'AT TIME',
      'OLT ADDED TIME',
      'HSTATUS',
      'HSTATUS CHANGE TIME',
      'STARTED USER',
      'CONFIGURED PIC COUNT',
      'CONFIGURED PON COUNT',
      'CONFIGURED ONT COUNT',
      'EMS CONNECTION TYPE',
      'EMS VLAN ID',
      'MARK FOR DELETE',
      'REMARKS',
      'OWNER',
    ],
    columns: [
      'report_id',
      'gp_code',
      'network_provider',
      'district',
      'block',
      'olt_location',
      'olt_loc_code',
      'olt_name',
      'olt_ip',
      'ems_name',
      'point_asset_code',
      'vendor',
      'tech_name',
      'version',
      'olt_state',
      'state_change_time',
      'commission_date',
      'nms_config_date',
      'at_time',
      'olt_added_time',
      'h_status',
      'h_status_change_time',
      'started_user',
      'conf_pic_count',
      'conf_pon_count',
      'conf_ont_count',
      'ems_conn_type',
      'ems_vlan_id',
      'mark_for_del',
      'remarks',
      'owner',
    ],
  },
  'ont-net-provider': {
    headers: [
      'NETWORK PROVIDER',
      'DISTRICT',
      'BLOCK',
      'PANCHAYAT',
      'ONT LOCATION',
      'ONT LOCATION CODE',
      'EMS NAME',
      'OLT LOCATION',
      'ONT SERIAL NO',
      'OLT IP',
      'POINT ASSET CODE',
      'VENDOR',
      'TECH NAME',
      'VERSION',
      'PHYSICAL DISTANCE(metres)',
      'PIC ID',
      'PON ID',
      'ONT ID',
      'ONT STATE',
      'APP STATUS',
      'PHYSICAL STATUS',
      'SPV',
      'STATE CHANGE TIME',
      'COMMISSION DATE',
      'AT TIME',
      'NMS CONFIG DATE',
      'ONT ADDED TIME',
      'ONT DOWN ALARMS',
      'MARK FOR DELETE',
      'BHARATNET',
      'REMARKS',
      'TIME STAMP',
    ],
    columns: [
      'report_id',
      'gp_code',
      'network_provider',
      'district',
      'block',
      'panchayat',
      'ont_location',
      'ont_loc_code',
      'ems_name',
      'olt_location',
      'ont_serial_no',
      'olt_ip',
      'point_asset_code',
      'vendor',
      'tech_name',
      'version',
      'physical_dist',
      'pic_id',
      'pon_id',
      'ont_id',
      'ont_state',
      'app_status',
      'phys_status',
      'spv',
      'state_change_time',
      'commission_date',
      'at_time',
      'nms_config_date',
      'ont_added_time',
      'ont_down_alarms',
      'mark_for_delete',
      'bharat_net',
      'remarks',
      'timestamp',
    ],
  },
  'ont-ticket': {
    headers: [
      'State',
      'District',
      'Block',
      'Panchayat',
      'GP Location',
      'GP Location Code',
      'OLT Location',
      'EMS Name',
      'Serial No',
      'Alarm Cause',
      'Bin Type',
      'Current Alarm Name',
      'Bin Start Time',
      'Alarm Occurrence Time',
      'Ticket Id',
      'Problem Description',
      'Ticket Created Time',
      'Ticket Type',
      'Category',
      'OLT IP',
      'Vendor',
      'Tech Name',
      'Physical Distance',
      'PIC ID',
      'PON ID',
      'GP ID',
      'GP Status',
      'APP Status',
      'Physical Status',
      'SPV',
      'State Change Time',
      'Commission Date',
      'GP Added Date',
      'Owner',
      'Phase',
      'Temp Resolved',
      'Bharatnet',
    ],
    columns: [
      'report_id',
      'gp_code',
      'state',
      'district',
      'block',
      'panchayat',
      'gp_location',
      'gp_location_code',
      'olt_location',
      'ems_name',
      'serial_no',
      'alarm_cause',
      'bin_type',
      'current_alarm_name',
      'bin_start_time',
      'alarm_occurence_time',
      'ticket_id',
      'problem_description',
      'ticket_created',
      'ticket_type',
      'category',
      'olt_ip',
      'vendor',
      'tech_name',
      'physical_dist',
      'pic_id',
      'pon_id',
      'gp_id',
      'gp_state',
      'app_status',
      'physical_status',
      'spv',
      'state_change_time',
      'commission_date',
      'gp_added_date',
      'owner',
      'phase',
      'temp_resolved',
      'bharat_net',
    ],
  },
  'unknown-ont': {
    headers: [
      'NETWORK PROVIDER',
      'ONT LOCATION',
      'ONT LOCATION CODE',
      'EMS NAME',
      'OLT LOCATION',
      'ONT SERIAL NO',
      'OLT IP',
      'POINT ASSET CODE',
      'VENDOR',
      'TECH NAME',
      'VERSION',
      'PHYSICAL DISTANCE(metres)',
      'PIC ID',
      'PON ID',
      'ONT ID',
      'ONT STATE',
      'APP STATUS',
      'PHYSICAL STATUS',
      'SPV',
      'STATE CHANGE TIME',
      'COMMISSION DATE',
      'AT TIME',
      'NMS CONFIG DATE',
      'ONT ADDED TIME',
      'ONT DOWN ALARMS',
      'MARK FOR DELETE',
      'REMARKS',
      'TIME STAMP',
    ],
    columns: [
      'report_id',
      'gp_code',
      'network_provider',
      'ont_location',
      'ont_loc_code',
      'ems_name',
      'olt_location',
      'ont_serial_no',
      'olt_ip',
      'point_asset_code',
      'vendor',
      'tech_name',
      'version',
      'physical_dist',
      'pic_id',
      'pon_id',
      'ont_id',
      'ont_state',
      'app_status',
      'phys_status',
      'spv',
      'state_change_time',
      'commission_date',
      'at_time',
      'nms_config_date',
      'ont_added_time',
      'ont_down_alarms',
      'mark_for_delete',
      'remarks',
      'timestamp',
    ],
  },
  'mismatch-ont': {
    headers: [
      'ONT NAME',
      'OLT ID',
      'OLT NAME',
      'NETWORK PROVIDER',
      'PANCHAYAT',
      'ONT LOCATION',
      'ONT LOCATION CODE',
      'OLT LOCATION',
      'EMS',
      'ONT',
      'SERIAL NO',
      'OLT IP',
      'VERSION',
      'VENDOR',
      'PIC ID',
      'PON ID',
      'ONT ID',
      'ONT TYPE',
      'OLT_PIC_PON_ID',
      'GUI NAME',
      'ONTSTATE',
      'STATE',
      'APP STATUS',
      'PHYSICAL STATUS',
      'STATE CHANGE TIME',
      'NW ENTRY TIME',
      'LOG TIME',
      'REMARKS',
    ],
    columns: [
      'report_id',
      'gp_code',
      'ont_name',
      'olt_id',
      'olt_name',
      'network_provider',
      'panchayat',
      'ont_location',
      'ont_location_code',
      'olt_location',
      'ems',
      'ont_serial_no',
      'olt_ip',
      'version',
      'vendor',
      'pic_id',
      'pon_id',
      'ont_id',
      'ont_type',
      'olt_pic_pon_id',
      'gui_name',
      'ont_state',
      'state',
      'app_status',
      'physical_status',
      'state_change_time',
      'nw_entry_time',
      'log_time',
      'remarks',
    ],
  },
  'olt-status': {
    headers: [
      'DISTRICT',
      'UNREACHABLE',
      'OLT UP',
      'GRAND TOTAL',
      'PERCENTAGE OLT UP',
    ],
    columns: [
      'report_id',
      'district',
      'unreachable',
      'up',
      'grand_total',
      'percent_olt_up',
    ],
  },
  'ont-status': {
    headers: [
      'DISTRICT',
      'DOWN',
      'OPERATIONAL',
      'UNKWOWN PREV UP',
      'GRAND TOTAL',
      'PERCENTAGE OF ONT UP',
    ],
    columns: [
      'report_id',
      'district',
      'down',
      'operational',
      'unknown_prev_up',
      'total_ont_up',
      'grand_total',
      'percent_ont_up',
    ],
  },
  'mark-for-del': {
    headers: ['NE NAME', 'DISTRICT', 'COUNT OF PANCHAYAT'],
    columns: ['report_id', 'ne_name', 'district', 'count_panchayat'],
  },
  'loc-config-pending': {
    headers: ['NE NAME', 'DISTRICT', 'COUNT OF ONT LOCATION'],
    columns: ['ne_name', 'district', 'count_ont_loc'],
  },
};

export default reportArr;
